export const LOGIN_BACKGROUND_REQUEST = 'LOGIN_BACKGROUND_REQUEST';
export const LOGIN_BACKGROUND_SUCCESS = 'LOGIN_BACKGROUND_SUCCESS';
export const LOGIN_BACKGROUND_ERROR = 'LOGIN_BACKGROUND_ERROR';

export const CREATE_BACKGROUND_REQUEST = 'CREATE_BACKGROUND_REQUEST';
export const CREATE_BACKGROUND_SUCCESS = 'CREATE_BACKGROUND_SUCCESS';
export const CREATE_BACKGROUND_ERROR = 'CREATE_BACKGROUND_ERROR';

export const UPDATE_BACKGROUND_REQUEST = 'UPDATE_BACKGROUND_REQUEST';
export const UPDATE_BACKGROUND_SUCCESS = 'UPDATE_BACKGROUND_SUCCESS';
export const UPDATE_BACKGROUND_ERROR = 'UPDATE_BACKGROUND_ERROR';

export const GET_BACKGROUND_REQUEST = 'GET_BACKGROUND_REQUEST';
export const GET_BACKGROUND_SUCCESS = 'GET_BACKGROUND_SUCCESS';
export const GET_BACKGROUND_ERROR = 'GET_BACKGROUND_ERROR';
