export const LOGIN_CAMO_REQUEST = 'LOGIN_CAMO_REQUEST';
export const LOGIN_CAMO_SUCCESS = 'LOGIN_CAMO_SUCCESS';
export const LOGIN_CAMO_ERROR = 'LOGIN_CAMO_ERROR';

export const CREATE_CAMO_REQUEST = 'CREATE_CAMO_REQUEST';
export const CREATE_CAMO_SUCCESS = 'CREATE_CAMO_SUCCESS';
export const CREATE_CAMO_ERROR = 'CREATE_CAMO_ERROR';

export const UPDATE_CAMO_REQUEST = 'UPDATE_CAMO_REQUEST';
export const UPDATE_CAMO_SUCCESS = 'UPDATE_CAMO_SUCCESS';
export const UPDATE_CAMO_ERROR = 'UPDATE_CAMO_ERROR';

export const GET_CAMO_REQUEST = 'GET_CAMO_REQUEST';
export const GET_CAMO_SUCCESS = 'GET_CAMO_SUCCESS';
export const GET_CAMO_ERROR = 'GET_CAMO_ERROR';
