export const LOGIN_TEST_REQUEST = 'LOGIN_TEST_REQUEST';
export const LOGIN_TEST_SUCCESS = 'LOGIN_TEST_SUCCESS';
export const LOGIN_TEST_ERROR = 'LOGIN_TEST_ERROR';

export const CREATE_TEST_REQUEST = 'CREATE_TEST_REQUEST';
export const CREATE_TEST_SUCCESS = 'CREATE_TEST_SUCCESS';
export const CREATE_TEST_ERROR = 'CREATE_TEST_ERROR';

export const UPDATE_TEST_REQUEST = 'UPDATE_TEST_REQUEST';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_ERROR = 'UPDATE_TEST_ERROR';

export const GET_TEST_REQUEST = 'GET_TEST_REQUEST';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_ERROR = 'GET_TEST_ERROR';
